name: Feature Request
description: Request a new feature for Lexi
title: "[Feature Request]: "
labels: ["feature-request"]
assignees: Dzheremi2
body:
  - type: checkboxes
    attributes:
      label: Validation checkboxes
      description: Required checkboxes (if not checkmarked, then issue will be marked as invalid)
      options:
        - label: I have searched for my feature request around issue tracker and didn't find anything (closed issues count as well)
          required: true
        - label: I'm using English language for this issue. Non-English issue will be marked as invalid
          required: true
        - label: I declare that this issue is not a question. If you want to ask something, go to the Discussions
          required: true
        - label: Please stay tuned for messages from the contributors to your feature request. Don't keep them waiting too long
          required: true
  - type: textarea
    attributes:
      label: Feature description
      description: Description of the feature you want to be implemented
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: The way you would like this issue to be solved
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: Some info that may help to resolve this feature request
    validations:
      required: false